spring:
  application:
    name: knowledge-foundation-data
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true

