services:

  mysql:
    image: 'mysql:8.4.7'
    container_name: 'mysql'
    ports:
      - "3306:3306"
    volumes:
      - 'mysql_dev:/var/lib/mysql'
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=a2882131
    networks:
      - knowledge_network

  redis:
    image: 'redis:8.4.0'
    container_name: 'redis'
    restart: always
    ports:
      - '6379:6379'
    environment:
      - TZ=Asia/Shanghai
    command: [
      "redis-server",
      "--requirepass a2882131",
    ]
    volumes:
      - 'redis_dev:/data:rw'
    networks:
      - knowledge_network

networks:
  knowledge_network:
    driver: bridge

  dify_network:
    name: docker_default
    external: true

volumes:
  mysql_dev:
  redis_dev: